/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package supranational.blst;

public class PT {
  private transient long[] swigCPtr;

  protected PT(long[] cPtr) { swigCPtr = cPtr; }

  protected static long[] getCPtr(PT obj) {
    return obj != null ? obj.swigCPtr : null;
  }

  public PT dup() { return new PT(swigCPtr.clone()); }

  public PT(P1_Affine p) { this(blstJNI.new_PT__SWIG_0(P1_Affine.getCPtr(p))); }

  public PT(P2_Affine p) { this(blstJNI.new_PT__SWIG_1(P2_Affine.getCPtr(p))); }

  public PT(P2_Affine p2, P1_Affine p1) { this(blstJNI.new_PT__SWIG_2(P2_Affine.getCPtr(p2), P1_Affine.getCPtr(p1))); }

  public boolean is_one() {
    return blstJNI.PT_is_one(swigCPtr);
  }

  public boolean is_equal(PT p) {
    return blstJNI.PT_is_equal(swigCPtr, PT.getCPtr(p));
  }

  public PT sqr() { blstJNI.PT_sqr(swigCPtr); return this; }

  public PT mul(PT p) { blstJNI.PT_mul(swigCPtr, PT.getCPtr(p)); return this; }

  public PT final_exp() { blstJNI.PT_final_exp(swigCPtr); return this; }

  public static boolean finalverify(PT gt1, PT gt2) {
    return blstJNI.PT_finalverify(PT.getCPtr(gt1), PT.getCPtr(gt2));
  }

}
